version: 2.1

orbs:
  codacy: codacy/base@0.3.8

jobs:
  run-codacy-plugins-test:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: codacy-plugins-test-cache-$CODACY_PLUGINS_TEST_VERSION
      - attach_workspace:
          at: ~/
      - run:
          command: |
            mkdir -p codacy-plugins-test
            cd codacy-plugins-test
            FILENAME=codacy-plugins-test-$CODACY_PLUGINS_TEST_VERSION
            if [ ! -f "$FILENAME" ]; then
              wget https://bintray.com/codacy/Binaries/download_file?file_path=$CODACY_PLUGINS_TEST_VERSION%2Fcodacy-plugins-test-linux -O $FILENAME
              chmod +x $FILENAME
            fi
            docker load --input ~/workdir/docker-image.tar
            ./$FILENAME json $CIRCLE_PROJECT_REPONAME:latest
            ./$FILENAME pattern $CIRCLE_PROJECT_REPONAME:latest
      - save_cache:
          key: codacy-plugins-test-cache-$CODACY_PLUGINS_TEST_VERSION
          paths:
            - ~/codacy-plugins-test
    environment:
      CODACY_PLUGINS_TEST_VERSION: 0.0.1

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: publish_docker_local
          cmd: |
            sbt "set scalafmtUseIvy in ThisBuild := false;
                 scalafmt::test;
                 test:scalafmt::test;
                 sbt:scalafmt::test;
                 set name := \"$CIRCLE_PROJECT_REPONAME\";
                 set version in Docker := \"latest\";
                 docker:publishLocal"
            docker save --output ~/workdir/docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - run-codacy-plugins-test:
          requires:
            - publish_docker_local
      - codacy/sbt:
          name: publish_dockerhub
          context: CodacyDocker
          cmd: |
            docker load --input ~/docker-image.tar
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:latest
            docker push codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker push codacy/$CIRCLE_PROJECT_REPONAME:latest
          requires:
            - run-codacy-plugins-test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - publish_dockerhub
