version: 2.1

orbs:
  codacy: codacy/base@0.1.0

# Re-usable blocks to reduce boilerplate in job definitions.
references:
  set_version_env_variable: &set_version_env_variable
    run:
      name: Define Environment Variable VERSION_NUMBER and ENV at Runtime
      cmd: |
        echo export VERSION_NUMBER=$(cat .version) >> $BASH_ENV
        source $BASH_ENV
        echo $VERSION_NUMBER

  host_environment_defaults: &host_environment_defaults
    # Customize the JVM maximum heap limit
    JAVA_OPTS: -Xmx3200m

  default_java_job: &default_java_job
    machine: true
    environment:
      <<: *host_environment_defaults
    working_directory: ~/workdir

jobs:
  publish_local:
    <<: *default_java_job
    steps:
      - attach_workspace:
          at: ~/
      - codacy/sbt_cached:
          cmd:  |
            sbt workerApiServer/docker:publishLocal &&\
            docker save --output ~/docker-image.tar codacy/worker-api:$(cat .version)
      - persist_to_workspace:
          root: ~/
          paths:
            - docker-image.tar

  publish_dockerhub:
    <<: *default_java_job
    steps:
      - attach_workspace:
          at: ~/
      - *set_version_env_variable
      - run:
          name: Test patterns
          working_directory: ~/codacy-plugins-test
          cmd: sbt -Dcodacy.tests.noremove=true -Dcodacy.tests.threads=8 "runMain codacy.plugins.DockerTest pattern $CIRCLE_PROJECT_REPONAME:latest"
      - deploy:
          name: Push application Docker image
          cmd: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME
              docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:1.0.$CIRCLE_BUILD_NUM
              docker push codacy/$CIRCLE_PROJECT_REPONAME
            fi

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: populate_cache
          cmd: |
            git clone --depth 1 git://github.com/codacy/codacy-plugins-test.git codacy-plugins-test
            sbt ";set scalafmtUseIvy in ThisBuild := false;update"
            (cd codacy-plugins-test && sbt ";set scalafmtUseIvy in ThisBuild := false;update")
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: check_fmt
          cmd: sbt ";scalafmt::test;test:scalafmt::test;sbt:scalafmt::test"
          requires:
            - populate_cache
      - codacy/sbt:
          name: compile
          cmd: sbt compile
          requires:
            - check_fmt
      - codacy/sbt:
          name: test_patterns
          cmd: |
            sbt ";set name := \"$CIRCLE_PROJECT_REPONAME\";docker:publishLocal"
            (cd codacy-plugins-test && sbt -Dcodacy.tests.ignore.descriptions=true "runMain codacy.plugins.DockerTest json $CIRCLE_PROJECT_REPONAME:$(cat .version)")
          requires:
            - compile
      - codacy/sbt:
          name: publish_dockerhub
          context: CodacyDocker
          cmd: |
            sbt ";set name := \"$CIRCLE_PROJECT_REPONAME\";docker:publishLocal"
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:latest
            docker push codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker push codacy/$CIRCLE_PROJECT_REPONAME:latest
          requires:
            - test_patterns
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - publish_dockerhub
